class ArtObj1:
   def __init__(self):
      print '           H||'
      print '           H||'
      print ' __________H||___________'
      print '[|.......................|'
      print '||.........   #  # ......|            @@@@'
      print '||........     -^........|   ,      - @@@@'
      print '||....#####     /###.....|   |     __\@ \@'
      print '||..####,   ))/ ##.......|   |(__/ /     /|% #/'
      print '||..#####\____/#####.....|       ,:    ( '
      print '||.....""""  """"...b ger|       |:      )'
      print '       H||_______H||             |_____,_|'
      print '       H||       H||              (  \| /'
      print '    H|________________|            =>/   '
      print '                                 /  \ /|/'

class ArtObj2:
   def __init__(self):
      print ' ________________________'
      print '|.----------------------.|'
      print '||                      ||'
      print '||                      ||'
      print '||     .-"````"-.       ||'
      print '||    /  _.._    `\     ||'
      print '||   / /`    `-.   ; . .||'
      print '||   | |__  __  \   |   ||'
      print '||   | |  |     |   | --||'
      print '||   |  \ --   /|   |   ||'
      print '||   |   `;--- \|   |   ||'
      print '||   |    |     |   |   ||'
      print '||   |  .-      |   |   ||'
      print '|| --|/`        |   |--.||'
      print '||   ;    .     ;  _.\  ||'
      print '||    `-.;_    /.-      ||'
      print '||         ````         ||'
      print '||jgs___________________||'
      print ' ------------------------ '

class ArtObj3:
   def __init__(self):
      print '   **%'
      print '   ====='
      print '  &%&**%&'
      print '  %& < <% '
      print '   &\__/'
      print '   \ |____'
      print '  . , ,  ()'
      print ' / -.  _)|' 
      print '|_(_.    |'
      print ' - \  )  |'
      print 'mrf )    |'
      print '    /  .  ).'
      print '  /    _. |'
      print ' / --- :.-  '
      print '(__.        '
      print ' \   ( /  /'
      print '  \ /  _  | '
      print '   \  |  ' ''
      print '  | . \  |'
      print '   |(     |'
      print '   |  \ \ |'
      print '   \  )\ |'
      print '   __)/ /  '
      print '-- --(_.Ooo ----'

class ArtObj4:
   def __init__(self):
      print 'b.'
      print '88b'
      print '888b.'
      print '88888b'
      print '888888b.'
      print '8888P'
      print 'P" `8.'
      print '    `8.   cgmm'

class ArtObj5:
   def __init__(self):
      print '   ___/ ___________'
      print ' / ___/           _____'
      print ' / /              (____ '
      print '| |  E V 1 L           \ '
      print '| |      1 N 5 1 D E    ) )'
      print ' \ \__               __/ /           __'
      print '  \__ \_____________/ __/        ___/  '
      print '     \_______________/       ___/       \_'
      print '                        ___/             '
      print '                     ___/   __/            \_'
      print '                 ___/   __  \__/\           \_'
      print '             ___/    __/        _\      ___/|'
      print '        ____/    __     \      /    ___/ _  ('
      print '       /        \ /_     \      ___/ _   \_ |'
      print '       |\  __    \  /       ___/ _   \_  _H_/'
      print '      | \/  \    \/    ___/ _   \_  _H_/ Y'
      print '       |`|  _/      ___/ _   \_  _H_/ Y   !   MEPH.'
      print '        \|_|\   ___/ _   \_  _H_/ Y   !   !'
      print '        !  | \_/ _   \_  _H_/ Y   !   !'
      print '        !  \` |  \_  _H_/ Y   !   !'
      print '            \`|  _H_/ Y   !   !'
      print '             \|_/ Y   !   !'
      print '                  !   !'

class ArtObj6:
   def __init__(self):
      print '       /\    ___---'
      print '------/  \---'
      print '-----/    \---------'
      print '----/      \---___'
      print '   /        \     ---'
      print '  /__________\_'

class ArtObj7:
   def __init__(self):
      print '   |'
      print ' \ |  /'
      print '  \* /'
      print '--**O**-- '
      print '  /* \_'
      print '/  |  \_'
      print '   |'

class ArtObj8:
   def __init__(self):
      print ' ;,//;,    ,;/'
      print 'o:::::::;;///'
      print '>::::::::;;\_\_'
      print '  \_\_ "  ;_'

class ArtObj9:
   def __init__(self):
      print '[bug]     /"*._         _'
      print '     .-*       *-.._.-  _'
      print '    < * ))     ,       ( '
      print '     `*-._`._(__.--*"`.\_'

class ArtObj10:
   def __init__(self):
      print '          A'
      print '         /!\_'
      print '        / ! \_'
      print ' /\     )___('
      print '(  `.____(_)_________'
      print '|           __..--""'
      print '(       _.-|'
      print ' \    ,  | |'
      print '  \  /   | |'
      print '   \(    | |'
      print '    `    | |'
      print '         | |'

class ArtObj11:
   def __init__(self):
      print '                /\_[]_/\_'
      print '        ___     \/ || \/'
      print '      (|0 0|)      ||'
      print '   / \  {~}   / _|_P|'
      print '   |_| (____)    '    
      print '      _\_||_/_  '         
      print ' snd (_,_||_,_)'

class ArtObj12:
   def __init__(self):
      print '                             Y\     /Y'
      print '                             | \ _ / |'
      print '       _____                 | =(_)= |'
      print '   ,-~"     "~-.           ,-~\/^ ^\/~-.'
      print '  ,^ ___     ___ ^.       ,^ ___     ___ ^.'
      print ' / .^   ^. .^   ^. \     / .^   ^. .^   ^. \_'
      print 'Y  l    O! l    O!  Y   Y  lo    ! lo    !  Y'
      print 'l_ `.___.  `.   . _[   l_ ` .___.  `.___.  _['
      print 'l^~"-------------"~^I   l^~"-------------"~^I'
      print '!\,               ,/!   !                   !'
      print ' \ ~-.,_______,.-~ /     \                 /'
      print ' ^.             .^       ^.             .^    -Row'
      print '   "-.._____.,-"           "-.._____.,-"'
      print '                                                  '
      print '              ->Mr&MrsPacman<-'
      print 'Norns by Shanaka Dias'

class ArtObj13:
   def __init__(self):
      print '        _____'
      print '    .-,;='';_),-.'
      print '     \_\(),()/_/'
      print '       (,___,)'
      print '     ,-/`~`\-,___'
      print '    / /).:.(  .  )'
      print '   {_[ (_,_)'
      print '       | Y |'
      print '      /  |  \_'
      print '      """ """ '

class ArtObj914:
   def __init__(self):
      print '                        .-.'
      print '                        ' ''
      print '                       //'
      print '              _..---._/|'
      print '            . ."      -.'
      print '           /__/          \      *'
      print '          ====_____     __|     :'
      print '         /#   #""" |   /()\    :    ..*'
      print '         |#   #    |   \__/    : .'' '
      print '          \#___#____|      /   :::.. .'
      print '  ()       // /\||||)))))))         . .'
      print ' .( \_      \_\//   _- . /        |   * ..'
      print '(_)_. v|v|v|     / \#  \_ /  _  _     . .   '
      print '           /#_#__"""-._ /#  \__)       .  .   '
      print '           |__   ""-._ |##               . . .'
      print '           |  ""|-"""-_/##              . .    '
      print '           /-_| /  \_'
      print '           \        |                      .  .'
      print '           <_-/ <_.-\                    .'
      print '           <_-|  |_.-|                        .'
      print '      .----|   \__\  |                 .'
      print '      .___|        |__|  (c) NamelessOne'
      
class ArtObj15:
   def __init__(self):
      print '      ____                   '
      print '     /___/\_                 '
      print '    _\   \/_/\__             '
      print '  __\       \/_/\            '
      print '  \   __    __ \ \           '
      print ' __\  \_\   \_\ \ \   __     '
      print '/_/ \   __   __  \ \_/_/\    '
      print '\_\/_\__\/\__\/\__\/_\_\/    '
      print '   \_\/_/\       /_\_\/      '

class ArtObj16:
   def __init__(self):
      
      print '                __'
      print '              _|  |_'
      print '            _|      |_'
      print '           |  _    _  |'
      print '           | |_|  |_| |'
      print '        _  |  _    _  |  _'
      print '       |_|_|_| |__| |_|_|_|'
      print '         |_|_        _|_|'

class ArtObj17:
   def __init__(self):
      print '      [ ]'
      print '     (   )'
      print '      |>|'
      print '   __/===\__'
      print '  //| o=o |\_'
      print '<]  | o=o |  [>'
      print '    \=====/'
      print '   / / | \ \_'
      print '  <_________>'

class ArtObj18:
   def __init__(self):
      print '       .-""""-.        .-""""-.'
      print '      /        \      /        \_'
      print '     /_        _\    /_        _\_'
      print '    // \      /  |  // \      /  \_'
      print '    |\__\    /__/|  |\__\    /__/|'
      print '     \    ||    /    \    ||    /'
      print '      \        /      \        /'
      print '       \  __  /        \  __  /' 
      print '         .__.            .__.'
      print '         |  |            |  |'
      print 'jgs      |  |            |  |'

class ArtObj19:
   def __init__(self):
      print '    /\_'
      print '   /  \_'
      print '  |    |'
      print '  |NASA|'
      print '  |    |'
      print '  |    |'
      print '  |    |'
      print ' :      :'
      print ' |      |'
      print ' |      |'
      print ' |______|'
      print '   `  `  .'
      print '  / . \_' ''
      print '   ( . \. .;'
      print ''             ' AsH'

class ArtObj20:
   def __init__(self):
      print 'a peek into the night sky'
      print '||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||'
      print '||            +             +                  +   @          ||'
      print '||   |                *           o     +                .    ||'
      print '||  -O-    o               .               .          +       ||'
      print '||   |                    _,.-----.,_         o    |          ||'
      print '||           +    *    .- .         . -.          -O-         ||'
      print '||      *            . .     .   .   ` . .                    ||'
      print '|| .                /_.-              .  ._                   ||'
      print '||           -=*<  |-._.-  |   @   |    -._|  >*=-    .     + ||'
      print '|| -- )--           \`-.    \     /    .- /                   ||'
      print '||       *     +     `. .     ---     . .     +       o       ||'
      print '||                  .   -._         _.-   .                   ||'
      print '||         |               `~~~~~~~`       - --===D       @   ||'
      print '||   o    -O-      *   .                  *        +          ||'
      print '||         |                      +         .            +    ||'
      print '|| jgs          .     @      o                        *       ||'
      print '||       o                          *          o           .  ||'
      print '||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||'

class ArtObj21:
   def __init__(self):
      print '         _nnnn_'
      print '        dGGGGMMb'
      print '       @p~qp~~qMb'
      print '       M|@||@) M|'
      print '       @,----.JM|'
      print '      JS^\__/  qKL'
      print '     dZP        qKRb'
      print '    dZP          qKKb'
      print '   fZP            SMMb'
      print '   HZM            MMMM'
      print '   FqM            MMMM'
      print ' __| ".        |\dS"qML'
      print ' |    `.       | `   Zq'
      print '_)      \.___.,|     .'
      print '\____   )MMMMMP|   .'
      print '     -          -- hjm'

class ArtObj22:
   def __init__(self):
      print '       .---.'
      print '      /     \_'
      print '      \.@-@./'
      print '      /`\_/`\_'
      print '     //  _  \_'
      print '    | \     )|_'
      print '   /`\_`>  <_/ '
      print 'jgs\__/ --- \__/'

class ArtObj23:
   def __init__(self):
      print '    ___      ___'
      print '   /    ____/    '
      print '  /    / __       '
      print ' /    |  ..  |     '
      print '  ___/|      | ___/ '
      print '    | |_|  |_|       '
      print '   | |/|__| |        '
      print '    |   |__|         | '
      print '    |   |__|   |_/  /   '
      print '    | @ |  | @ || @ |   '
      print '    |   |~~|   ||   |     -Hamilton Furtado-'
      print '     ooo    ooo  ooo '

class ArtObj24:
   def __init__(self):
      print '   :::::::::::``  ``::`      `::::::  `:::::::::::::`.:::::::::::::::'
      print '   :::::::::, :. :  :         ::::::  :::::::::::.:::,:::::::::::::::'
      print '   ::::::::::  :   :::.       :::::::::::::..::::,     :::: : :::::::'
      print '   ::::::::    :,:  "::,     ,"::::::::::::: :,           ,, ,:::::::'
      print '   :,        : ,   :  ::    .::::::::,    ,                        .:'
      print '   :               :  .:: .::. ::::,                              :::'
      print '   :. .,.        :::  ,:::::::::::.: ,                      .:...::::'
      print '   :::::::.      ,     .::::::: ,,,                         :: :::::.'
      print '   ::::::::            ,:::::::::  ,,,            ,    ,   .:::::::::'
      print '   ::::::::.        :::::::::::: ,,:,:   ,    :         ,,, :::::::::'
      print '   ::::::::::      ::::::::::::,                        :::::::::::::'
      print '   : .::::::::.   .:,,::::::::    ,         ::   :   ,::.::::::::::::'
      print '   :::::::::::::::. ,  ,::::::.  ,  ,     :::::.:.:.:.:.:::::::::::::'
      print '   :::::::::::::::: :     ,:::::::::   , ,:::::::::: : :.:,::::::::::'
      print '   ::::::::::::::::: ,     :::::::::   . :,::::::::::::::, ,:::::::::'
      print '   ::::::::::::::::::,,   :::::::::: :, : ,:::::::::::,      ,:::::::'
      print '   :::::::::::::::::,   .::::::::::::  ::::::::::::::::       :::::::'
      print '   :::::::::::::::::. .::::::::::::::::::::::::::::::::::::.,::::::::'
      print '   :::::::::::::::::, :::::::::::::::::::::::::::::::::::::::::::::::'
      print '   ::::::::::::::::::.:::::::::::::::::::::::::::::::::::::::::::::::'

class ArtObj25:
   def __init__(self):
      print ' *    *    .  *    // *            .  *'
      print '     *  .  ..  *  //.     *      *        *    .'
      print '..    *  ___o |==//     .      *   *'
      print '        /    /  //|    *  .  ..   *       *'
      print 'ejm96  / /        |  '
      print '       ` `        `    `'



class ArtObj26:
   def __init__(self):
      print '    ,--._______,-.'
      print '   , `, `  ,    .  ,_`-.'
      print '  / /  , ` , _` ``. |  )       `-..'
      print ' (, `; `""`/  `"`-._ `  / ______    '  
      print '  : ,o.-`- ,o.  ) ` - `      `---.))'
      print '   : , d8b ^-.    `|   `.      `    `.'
      print '   |/ __:_     `. |  ,  `       `     '
      print '   | ( ,-.`-.    ; `  ;   `       :    ;'
      print '   | |  ,   `.      /     ;      :     '
      print '     ;- ``:::._,`.__), `             :     ;'
      print '        / ,  `-   `--                  ;     |'
      print '       /                      `       ,      |'
      print '       (    `     :              :    ,       |'
      print '        `.    :     :        :  , `       :'
      print '          `|-- `       , `    ,- `     :-.- `;'
      print '           :     |`--.______;     |        :    :'
      print '           :    /           |    |         |    '
      print '           |    ;           ;    ;        /     ;'
      print '         _/-- ` |   -hrr-   :`-- /          _:_:_|'
      print '     , `, `, `  |           |___  '
      print '        `^._,-- `           / , , .)'
      print '                            `-._,- `'



class ArtObj27:
   def __init__(self):
      print '                            ,s$$$Ss ,'
      print '               ,8,         $$$ , _ ,  ,               , ,sS$$$$$"   , , ,, ,;'
      print ' o ,   ,@ , ,  88        = ,$"$ `   `           , ,sS$$$$$$$$$$$$s , _;" `'
      print '  @@@ ,@@@ ,  ,88 ,   `  ` ""l ,  ,sS$$ , ,_ ,sS$$$$$$$$$$$$S `" `'
      print '    ,@@@q@@ ,8888o ,          ,s$$$$$$$$$$$$$$$$$$$$$ `'
      print '      ,:`@@@@33333 ,        ,>$$$$$$$$$$$$$$$$$$$$ `'
      print '      ,: `@@@@333 `        , ,>$$$$$$$$$$$$$$$$$$$ `'
      print '      :  `@@333 ,     ` ,,   s$$$$$$$$$$$$$$$$$ `'
      print '      :   `@33       $$ S ,s$$$$$$$$$$$$$$$$$ `'
      print '       ,S   `Y       , ,`  ,"$ ` `$$$$$$$$$$$$$$'
      print '      $s   ,        , ,S$s,     ,  ,`$$$$$$$$$$$$ ,'
      print '      $s  ,,      ,s ,$$$$,,sS$s ,$$$$$$$$$$$$$ ,'
      print '     /` ,`$$$$$dN ,ssS$$ ``$$$$$$$$$$$$$$$$$$$$$$$ ,'
      print '   ///|     `S$$S$ `       `$$$$$$$$$$$$$$$$$$$$$$ ,'
      print '  / /                      $$$$$$$$$$$$$$$$$$$$$ ,'
      print '                           `$$$$$$$$$$$$$$$$$$$$$s ,'
      print '                            $$$" `         ,?T$$$$$$$'
      print '                            ,$ `         , , ,      ?$$#' 
      print '                           !       -=S$$$$$s'
      print '                          ,!       -=s$$ `  `$=-_      :'
      print '                        ,         ,$$$ `     `$,        ,|'
      print '                       ,        ,$$$ `           ,        ,'
      print '                      ,      , ,$$$ `'
      print '                           ,s$$$ `                 `s      ,'
      print '                    ,    ,s$$$$ `                    $s ,  , ,$s'
      print '                   ,   ,s$$$$ `                      `$s=s$$$'
      print '                     ,$$$$ `                         ,    $$s'
      print '               `   "  ,$$ `                               $$$'
      print '               ,   s$$ `                               ,  $$$s'
      print '            `  ,s , ,s$ `                                 ,s ,$$'
      print '              ,s$$$ `                                   "s$$$,'
      print '          -   $$$ `                                      ,$$$$ ,'
      print '         ,"   ,s$$s                                      ,$ `, `,$ ,'
      print '        $s ,s$$$$S , , , , , , , , , , , , , ,    , , , , , , , , , , , , , , , ,    $$ , , , ,s$s , , , , , ,'
      print '         `"" `           `     ```"""""""""""""""         `""   ``'
      print '                                                          [banksy]dp'


class ArtObj28:
   def __init__(self):
      print '                                 ,_-=(!7(7/zs_.'
      print '                             .= `   ` .`/,/!(=)Zm.'
      print '               .._,,._..  ,-`- `,  ` -` -`  7//WW.'
      print '          ,v=~/.-,- - -!|V-s.)iT-|s| -. `   `///mK$.'
      print '        v!`i!-.e]-g`bT/i(/[=.Z/m)K(YNYi..   /-]i44M.'
      print '      v`/,`|v]-DvLcfZ/eV/iDLN D/ZK@$8W[Z..   `/d!Z8m'
      print '     //,c (2(X/NYNY8]ZZ/bZd ()/ 7WY$WKKW)   - `|(][$4.'
      print '   ,  i c(e)WX@WKKZKDKWMZ8(b5/ZK8]Z7$ffVM,   -.Y!bNMi'
      print '   /-iit5N)KWG$$8$$$$W8$ZWM(8YZvD)XN(@.  [    ]!/GXW['
      print '  / ))G8 NMN$W$$$$$$$$$$8KK@WZKYK*ZG5KMi,-   vi[NZGM['
      print ' i !(44Y8K$8$$$**~YZYZ@$$$$$4KWZ/PKN)ZDZ7   c=//WZK$!'
      print ', v YtMZW8W$$f`,`.t/bNZZK$$W$$ZXb*K(K5DZ   -c  /KM48'
      print '-|c5PbM4DDW$f  v./c [tMY8W$PMW$D@KW)Gbf   -/(=ZZKM8['
      print '2(N8YXWK85@K   - `c|K4/KKK$@  V$@@WD8e~  .//ct)8ZK$8`'
      print '=)b$]Nd)@KM[  ! ` cG!iWYK$$|   !M@KZf    -c ))ZDKW$`'
      print 'YYKWZGNM4/Pb   `-VscP4]b@W$      `Mf`   -L ///KM($W!'
      print '!KKW4ZK/W7)Z.  `/cttbY)DKW$     -`  . `, v)K(5KW$$f'
      print ' `W)KWKZZg)Z2/,!/L(-DYYb54$  ,,`, - -/v(((KK5WW$f'
      print '  M4NDDKZZ(e!/ 7vNTtZd)8 Mi! -,-/i-v((tKNGN$W$$'
      print '  `M8M88(Zd))///((|D tDY  KK-`/-i(=)KtNNN@W$$$@$['
      print '  !8$@KW5KKN4///s( Pd!ROBY8/=2(/4ZdzKD$K$$$M8@$$'
      print '    `$$$W$dGNtPK(c /2 [Z(ttNYZ2NZW8W8K$$$$YKM$M$$.'
      print '    *$$W$GW5@/$!e]_tZdY()v)ZXMZW$W$$$*5Y]K$ZK$8['
      print '       `*$$$$8$8WK )[/ZmZ/Zi]!/M$$$$@f   Y/NNMK$$!'
      print '         `VM$$$$W$WN5Z/Gt5/b)((cV@f`  - |cZbMKW$$|'
      print '            `V*M$$$WZ/ZG t5((+)L  `-,,/  -)X(NWW$$'
      print '                `~`MZ/DZGNZG5((( ,    ,t  Z)KW$@'
      print '                    `M8K$8GN8 5(5///]i!v K)85W$$f'
      print '                     YWWKKKKWZ8G54X/GGMeK@WM8$@'
      print '                      !M8$8$48WG@KWYbW$WWW$$$@'
      print '                        VM$WKWK$8K$$8WWWW$$$@`'
      print '                          ~*$$$$$$W$$$$$$$@~'
      print '                             ~*MM$$$$$$@f`'
      print '                                   ` ` ` ` `'


class ArtObj29:
   def __init__(self):
      print '                                        ,   ,'
      print '                                        $,  $,     ,'
      print '                                        "ss.$ss. .s`'
      print '                                ,     .ss$$$$$$$$$$s,'
      print '                                $. s$$$$$$$$$$$$$$`$$Ss'
      print '                                "$$$$$$$$$$$$$$$$$$o$$$ '      
      print '                               s$$$$$$$$$$$$$$$$$$$$$$$$s,  ,s'
      print '                              s$$$$$$$$$"$$$$$$""""$$$$$$"$$$$$,'
      print '                              s$$$$$$$$$$s""$$$$ssssss"$$$$$$$$"'
      print '                             s$$$$$$$$$$`         `"""ss"$"$s""'
      print '                             s$$$$$$$$$$,              `"""""$  .s$$s'
      print '                             s$$$$$$$$$$$$s,...               `s$$`  `'
      print '                         `ssss$$$$$$$$$$$$$$$$$$$$####s.     .$$"$.   , s-'
      print '                           `""""$$$$$$$$$$$$$$$$$$$$#####$$$$$$"     $.$`'
      print '                                 "$$$$$$$$$$$$$$$$$$$$$####s""     .$$$|'
      print '                                  "$$$$$$$$$$$$$$$$$$$$$$$$##s    .$$" $'
      print '                                   $$""$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"   `'
      print '                                  $$"  "$"$$$$$$$$$$$$$$$$$$$$S""""`'
      print '                             ,   ,"     `  $$$$$$$$$$$$$$$$####s'
      print '                             $.          .s$$$$$$$$$$$$$$$$$####"'
      print '                 ,           "$s.   ..ssS$$$$$$$$$$$$$$$$$$$####"'
      print '                 $           .$$$S$$$$$$$$$$$$$$$$$$$$$$$$#####"'
      print '                 Ss     ..sS$$$$$$$$$$$$$$$$$$$$$$$$$$$######""'
      print '                  "$$sS$$$$$$$$$$$$$$$$$$$$$$$$$$$########"'
      print '           ,      s$$$$$$$$$$$$$$$$$$$$$$$$#########""`'
      print '           $    s$$$$$$$$$$$$$$$$$$$$$#######""`      s`         ,'
      print '           $$..$$$$$$$$$$$$$$$$$$######"`       ....,$$....    ,$'
      print '            "$$$$$$$$$$$$$$$######"` ,     .sS$$$$$$$$$$$$$$$$s$$'
      print '              $$$$$$$$$$$$#####"     $, .s$$$$$$$$$$$$$$$$$$$$$$$$s.'
      print '   )          $$$$$$$$$$$#####`      `$$$$$$$$$###########$$$$$$$$$$$.'
      print '  ((          $$$$$$$$$$$#####       $$$$$$$$###"       "####$$$$$$$$$$'
      print '  )           $$$$$$$$$$$$####.     $$$$$$###"             "###$$$$$$$$$   s`'
      print ' (   )        $$$$$$$$$$$$$####.   $$$$$###"                ####$$$$$$$$s$$`'
      print ' )  ( (       $$"$$$$$$$$$$$#####.$$$$$###` -Tua Xiong     .###$$$$$$$$$$"'
      print ' (  )  )   _,$"   $$$$$$$$$$$$######.$$##`                .###$$$$$$$$$$'
      print ' ) (  (  .         "$$$$$$$$$$$$$#######,,,.          ..####$$$$$$$$$$$"'
      print '(   )$ )  )        ,$$$$$$$$$$$$$$$$$$####################$$$$$$$$$$$"'
      print '(   ($$  (       _sS"  `"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$S$$,'
      print ' )  )$$$s ) )  .      .   `$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"`  `$$'
      print '  (   $$$Ss/  .$,    .$,,s$$$$$$##S$$$$$$$$$$$$$$$$$$$$$$$$S""        `'
      print '     )_$$$$$$$$$$$$$$$$$$$$$$$##"  $$        `$$.        `$$.'
      print '        `"S$$$$$$$$$$$$$$$$$#"      $          `$          `$'
      print '            `"""""""""""""`         `           `           `'


class ArtObj30:
   def __init__(self):
      print ',     ,       ,  ,   , ,   ,   , ,    +  ,'
      print '  ,     ,  :     ,    ,, :, ,___---------___,'
      print '       ,  ,   ,    ,  :,:, _",^ ,^ ^,  `,, :"-_, ,'
      print '    ,  :       ,  ,  ,:,,/:            , ,^  :,: ,'
      print '        ,   , :: +, :,:/: ,   ,    ,        , , ,: '
      print ' ,  :    ,     , _ :::/:               ,  ^ ,  , ,: '
      print '  ,, , ,   , - : :,:,/,                        ,  ,: '
      print '  ,      ,     , :,,|:                    ,  ,  ^, ,:|'
      print '    ,       , : : ,,||        ,                , , !:|'
      print '  ,     , , , ::, :: (                           , :)/'
      print ' ,   ,     : , : ,:,|, ######              ,#######::|'
      print '  :,, ,  :-  : ,:  ::|,#######           ,,########:|'
      print ' ,  ,  ,  ,,  ,  ,, :  ########          :######## :/'
      print '  ,        ,+ :: : -,:  ########       , ########,:/'
      print '    ,  ,+   , , , , :,: , #######       #######,,:/'
      print '      :: , , , , ::,:,,:,            ,   ,   ,,:/'
      print '  ,   ,   ,  ,, :  -::::, ,       | |     , ,:/'
      print '     ,  :  ,  ,  ,-:,":,::,              ,,:/'
      print ' ,      -,   , , , ,: ,:::,:, ,           ,:/'
      print ',   ,   ,  :      : ,,,,::_:,,:    ___,  :/'
      print '   ,   ,  ,   ,:, ,, ,  ,: :,:,:        :/'
      print '     +   ,   ,   : , ::, :,:, ,:,|   ,:/|'
      print '     ,         +   ,  ,  ,,,:: ,,|  --,:|'
      print ',      , , ,   ,  ,  , ,,, :,,:,,"(  ,,)"'
      print ' ,   ,       ,      :  ,   ,: ::/  ,  ,:: '

class ArtObj31:
   def __init__(self):
      print '                     .ed"""" """$$$$be.'
      print '                   -"           ^""**$$$e.'
      print '                 ."                   `$$$c'
      print '                /                      "4$$b'
      print '               d  3                     $$$$'
      print '               $  *                   .$$$$$$'
      print '              .$  ^c           $$$$$e$$$$$$$$.'
      print '              d$L  4.         4$$$$$$$$$$$$$$b'
      print '              $$$$b ^ceeeee.  4$$ECL.F*$$$$$$$'
      print '  e$""=.      $$$$P d$$$$F $ $$$$$$$$$- $$$$$$'
      print ' z$$b. ^c     3$$$F "$$$$b   $"$$$$$$$  $$$$*"      .=""$c'
      print '4$$$$L         $$P"  "$$b   .$ $$$$$...e$$        .=  e$$$.'
      print '^*$$$$$c  $..   *c    ..    $$ 3$$$$$$$$$$eF     zP  d$$$$$'
      print '  "**$$$ec   "    $ce""    $$$  $$$$$$$$$$*    .r" =$$$$P""'
      print '        "*$b.  "c  *$e.    *** d$$$$$"L$$    .d"  e$$***"'
      print '          ^*$$c ^$c $$$      4J$$$$$$ $$$ .e*".eeP"'
      print '             "$$$$$$"`$=e....$*$$**$cz$$" "..d$*"'
      print '               "*$$$  *=$4.$ L L$ P3$$$F $$$P"'
      print '                  "$   "$*ebJLzb$e$$$$$b $P"'
      print '                    $..      4$$$$$$$$$$ "'
      print '                     $$$e   z$$$$$$$$$$$'
      print '                      "*$c  "$$$$$$$P"'
      print '                       ."""*$$$$$$$$bc'
      print '                    .-"    .$***$$$"""*e.'
      print '                 .-"    .e$"     "*$c  ^*b.'
      print '          .=*""""    .e$*"          "*bc  "*$e..'
      print '        .$"        .z*"               ^*$e.   "*****e.'
      print '        $$ee$c   .d"                     "*$.        3.'
      print '        ^*$E")$..$"                         *   .ee==d$'
      print '           $.d$$$*                           *  J$$$e*'
      print '            """""                             "$$$"   Gilo95`'



class ArtObj32:
   def __init__(self):
      print '                     ______'
      print '                  .-"      "-.'
      print '                 /             '
      print '                |              |'
      print '                |,  .-.  .-.  ,|'
      print '                | )(__/   __)( |'
      print '                |/     /       |'
      print '      (@_       (_     ^^     _)'
      print ' _     )  _______ __|IIIIII|__/__________________________'
      print '(_)@8@8(}<________|- IIIIII/-|___________________________>'
      print '       )_/                   /'
      print '      (@           `--------` jgs'


class ArtObj33:
   def __init__(self):
      print '                             ___ ,`'
      print '                         _~"|  ~~ ~, ,~`'
      print '                        /   :   /   /   _`'
      print '                       ?""  ;  `  ,`     )``'
      print '             /   ~-_  /   dp   ,    ,    |'
      print '          ,$"":    ,? |:    , ,   ,      |'
      print '         $    `,   ,  |:, , ,,  ,   ,   /'
      print '       /  `,   `,: : :| :   ,, , ,    _/'
      print '     / ~~~::,   ,:: ::, , ,::,:, ,,`~'
      print '       ::,,, ``,, : : : " , :, ,  ~~|    _____'
      print '     (:::, ,,   `,: ,:,::, : , : "/__-""     --'
      print '       )"",>  --~~~__, ::::*## :,:,:)  :    ,:` ~ '
      print '      |,,::`      >>    #######  `,: ,` ,  ,`     ?'
      print '       _,___      :``> ######### ::,",    ~ ,,~`" |,'
      print '           _">~____~~::, #* )#### :  ,,~       ,   )'
      print '         /:,:``;,:::_-  _-#####*:;: ::>,,          }'
      print '         o__o___q~_-" _-"###### ,:,``     ,,~~ ~    |'
      print '        ( o() &@&__--"  *::####::"  ";,,    ~~,,,::,)'
      print '       (o& O& O?S),`   ,:`:::*: :      ~~~,,,     "/'
      print '         oS $@&>/    ,:`  ::::: :,       ,~  "`,  {'
      print '          ~*~~""   __:/   "::::,,L        ~     ``/'
      print '          |::`    /##)     :`:::::          ,   $'
      print '           :; ,  |#/       : :::::::-___      -"'
      print '            ::::: |        : ::::::::::: ----"'
      print '            ::::::|:,      : :::::::::::|'
      print '            ::::::|`     , : ::::::::::::|'
      print '            -::::/       :,`::::::::::::/'
      print '             ~__/   ,   ;:,::::::::::_/       Eric Berger'
      print '                      ::,::::::::::::/'
      print '                       --_;::::::_-~/'
      print '                           """"""'














